added new packages and updated grow file

diff --git a/grow b/grow
--- a/grow
+++ b/grow
@@ -1,16 +1,36 @@
 #!/usr/bin/env bash
+
+### ERROR: display error if script failure. ###
+trap 'ret=$?; test $ret -ne 0 && printf "\n   \e[31m\033[0m  Germination failed  \e[31m\033[0m\n" >&2; exit $ret' EXIT
+
+set -e
+
+### Get required file ###
+if [ -e fertilise ]; then
+	cd "$(dirname "${BASH_SOURCE[0]}")" \
+		&& . "fertilise"
+else
+	printf "\n ⚠️  ./fertilise not found.\n"
+	exit 1
+fi
+
+### Run Script ###
+
 printf "
-   ___  ____  ____  __  __  ____  _  _    __   ____  ____ 
+  ___  ____  ____  __  __  ____  _  _    __   ____  ____ 
  / __)( ___)(  _ \(  \/  )(_  _)( \( )  /__\ (_  _)( ___)
 ( (_-. )__)  )   / )    (  _)(_  )  (  /(__)\  )(   )__) 
  \___/(____)(_)\_)(_/\/\_)(____)(_)\_)(__)(__)(__) (____)
 
-╭───────────────────────────────────────────────────╮
-│  Okay developers now let's get in ${bold}formation${normal}.      │
-│───────────────────────────────────────────────────│
-│  Safe to run multiple times on the same machine.  │
-│  It ${green}installs${reset}, ${blue}upgrades${reset}, or ${yellow}skips${reset} packages based   │
-│  on what is already installed on the machine.     │
-╰───────────────────────────────────────────────────╯
-   ${dim}$(get_os) $(get_os_version) ${normal} // ${dim}$BASH ${normal} // ${dim}$BASH_VERSION${reset}
+LET'S START ${bold}PLANTING${normal}!
+This is a shell script that aims to setup and/or maintain your Mac.
+The script will ${green}install${reset}, ${blue}upgrade${reset}, or ${yellow}skip${reset} packages based
+on what is already installed on the machine.
+
+${dim}OS: $(get_os) $(get_os_version) ${normal} // Shell: ${dim}$BASH ${normal} // Shell Version: ${dim}$BASH_VERSION${reset}
+${dim}Copyright © 2020 | Mathew Teague.${normal}
 "
+
+#open https://download.filezilla-project.org/client/FileZilla_3.46.3_macosx-x86_sponsored-setup.dmg
+
+#open https://get.popcorntime.sh/build/Popcorn-Time-0.3.10-Mac.zip
